// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

/**
 * Protobuf type {@code schedulePro.meeting.AddParticipantRequest}
 */
public  final class AddParticipantRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:schedulePro.meeting.AddParticipantRequest)
    AddParticipantRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddParticipantRequest.newBuilder() to construct.
  private AddParticipantRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddParticipantRequest() {
    meetingId_ = "";
    participantId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddParticipantRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            meetingId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            participantId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return schedulePro.meeting.MeetingServiceOuterClass.internal_static_schedulePro_meeting_AddParticipantRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return schedulePro.meeting.MeetingServiceOuterClass.internal_static_schedulePro_meeting_AddParticipantRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            schedulePro.meeting.AddParticipantRequest.class, schedulePro.meeting.AddParticipantRequest.Builder.class);
  }

  public static final int MEETING_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object meetingId_;
  /**
   * <code>string meeting_id = 1;</code>
   */
  public java.lang.String getMeetingId() {
    java.lang.Object ref = meetingId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      meetingId_ = s;
      return s;
    }
  }
  /**
   * <code>string meeting_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMeetingIdBytes() {
    java.lang.Object ref = meetingId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      meetingId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTICIPANT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object participantId_;
  /**
   * <code>string participant_id = 2;</code>
   */
  public java.lang.String getParticipantId() {
    java.lang.Object ref = participantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      participantId_ = s;
      return s;
    }
  }
  /**
   * <code>string participant_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getParticipantIdBytes() {
    java.lang.Object ref = participantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      participantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMeetingIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, meetingId_);
    }
    if (!getParticipantIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, participantId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMeetingIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, meetingId_);
    }
    if (!getParticipantIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, participantId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof schedulePro.meeting.AddParticipantRequest)) {
      return super.equals(obj);
    }
    schedulePro.meeting.AddParticipantRequest other = (schedulePro.meeting.AddParticipantRequest) obj;

    boolean result = true;
    result = result && getMeetingId()
        .equals(other.getMeetingId());
    result = result && getParticipantId()
        .equals(other.getParticipantId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEETING_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMeetingId().hashCode();
    hash = (37 * hash) + PARTICIPANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getParticipantId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static schedulePro.meeting.AddParticipantRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static schedulePro.meeting.AddParticipantRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schedulePro.meeting.AddParticipantRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(schedulePro.meeting.AddParticipantRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code schedulePro.meeting.AddParticipantRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:schedulePro.meeting.AddParticipantRequest)
      schedulePro.meeting.AddParticipantRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schedulePro.meeting.MeetingServiceOuterClass.internal_static_schedulePro_meeting_AddParticipantRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schedulePro.meeting.MeetingServiceOuterClass.internal_static_schedulePro_meeting_AddParticipantRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schedulePro.meeting.AddParticipantRequest.class, schedulePro.meeting.AddParticipantRequest.Builder.class);
    }

    // Construct using schedulePro.meeting.AddParticipantRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      meetingId_ = "";

      participantId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return schedulePro.meeting.MeetingServiceOuterClass.internal_static_schedulePro_meeting_AddParticipantRequest_descriptor;
    }

    @java.lang.Override
    public schedulePro.meeting.AddParticipantRequest getDefaultInstanceForType() {
      return schedulePro.meeting.AddParticipantRequest.getDefaultInstance();
    }

    @java.lang.Override
    public schedulePro.meeting.AddParticipantRequest build() {
      schedulePro.meeting.AddParticipantRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public schedulePro.meeting.AddParticipantRequest buildPartial() {
      schedulePro.meeting.AddParticipantRequest result = new schedulePro.meeting.AddParticipantRequest(this);
      result.meetingId_ = meetingId_;
      result.participantId_ = participantId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof schedulePro.meeting.AddParticipantRequest) {
        return mergeFrom((schedulePro.meeting.AddParticipantRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(schedulePro.meeting.AddParticipantRequest other) {
      if (other == schedulePro.meeting.AddParticipantRequest.getDefaultInstance()) return this;
      if (!other.getMeetingId().isEmpty()) {
        meetingId_ = other.meetingId_;
        onChanged();
      }
      if (!other.getParticipantId().isEmpty()) {
        participantId_ = other.participantId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      schedulePro.meeting.AddParticipantRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (schedulePro.meeting.AddParticipantRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object meetingId_ = "";
    /**
     * <code>string meeting_id = 1;</code>
     */
    public java.lang.String getMeetingId() {
      java.lang.Object ref = meetingId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meetingId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string meeting_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMeetingIdBytes() {
      java.lang.Object ref = meetingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meetingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string meeting_id = 1;</code>
     */
    public Builder setMeetingId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      meetingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string meeting_id = 1;</code>
     */
    public Builder clearMeetingId() {
      
      meetingId_ = getDefaultInstance().getMeetingId();
      onChanged();
      return this;
    }
    /**
     * <code>string meeting_id = 1;</code>
     */
    public Builder setMeetingIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      meetingId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object participantId_ = "";
    /**
     * <code>string participant_id = 2;</code>
     */
    public java.lang.String getParticipantId() {
      java.lang.Object ref = participantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        participantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string participant_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParticipantIdBytes() {
      java.lang.Object ref = participantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        participantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string participant_id = 2;</code>
     */
    public Builder setParticipantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      participantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string participant_id = 2;</code>
     */
    public Builder clearParticipantId() {
      
      participantId_ = getDefaultInstance().getParticipantId();
      onChanged();
      return this;
    }
    /**
     * <code>string participant_id = 2;</code>
     */
    public Builder setParticipantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      participantId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:schedulePro.meeting.AddParticipantRequest)
  }

  // @@protoc_insertion_point(class_scope:schedulePro.meeting.AddParticipantRequest)
  private static final schedulePro.meeting.AddParticipantRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new schedulePro.meeting.AddParticipantRequest();
  }

  public static schedulePro.meeting.AddParticipantRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddParticipantRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddParticipantRequest>() {
    @java.lang.Override
    public AddParticipantRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddParticipantRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddParticipantRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddParticipantRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public schedulePro.meeting.AddParticipantRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

