// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

public interface AddParticipantRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.meeting.AddParticipantRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meeting_id = 1;</code>
   */
  java.lang.String getMeetingId();
  /**
   * <code>string meeting_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMeetingIdBytes();

  /**
   * <code>string participant_id = 2;</code>
   */
  java.lang.String getParticipantId();
  /**
   * <code>string participant_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getParticipantIdBytes();
}
