// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.meeting.Empty)
    com.google.protobuf.MessageOrBuilder {
}
