// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

public interface MeetingNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.meeting.MeetingNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meeting_id = 1;</code>
   */
  java.lang.String getMeetingId();
  /**
   * <code>string meeting_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMeetingIdBytes();

  /**
   * <code>int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   */
  long getEndTime();
}
