// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

public final class MeetingServiceOuterClass {
  private MeetingServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_Meeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_Meeting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_ScheduleMeetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_ScheduleMeetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_ScheduleMeetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_ScheduleMeetingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_SharedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_SharedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_MeetingNotification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_MeetingNotification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_AddParticipantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_AddParticipantRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_meeting_RemoveParticipantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_meeting_RemoveParticipantRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024MeetingService.proto\022\023schedulePro.meet" +
      "ing\"u\n\007Meeting\022\n\n\002id\030\001 \001(\t\022\r\n\005title\030\002 \001(" +
      "\t\022\023\n\013description\030\003 \001(\t\022\022\n\nstart_time\030\004 \001" +
      "(\003\022\020\n\010end_time\030\005 \001(\003\022\024\n\014participants\030\006 \003" +
      "(\t\"G\n\026ScheduleMeetingRequest\022-\n\007meeting\030" +
      "\001 \001(\0132\034.schedulePro.meeting.Meeting\"%\n\027S" +
      "cheduleMeetingResponse\022\n\n\002id\030\001 \001(\t\"\007\n\005Em" +
      "pty\"!\n\016SharedResponse\022\017\n\007success\030\001 \001(\010\"O" +
      "\n\023MeetingNotification\022\022\n\nmeeting_id\030\001 \001(" +
      "\t\022\022\n\nstart_time\030\002 \001(\003\022\020\n\010end_time\030\003 \001(\003\"" +
      "C\n\025AddParticipantRequest\022\022\n\nmeeting_id\030\001" +
      " \001(\t\022\026\n\016participant_id\030\002 \001(\t\"F\n\030RemovePa" +
      "rticipantRequest\022\022\n\nmeeting_id\030\001 \001(\t\022\026\n\016" +
      "participant_id\030\002 \001(\t2\207\004\n\016MeetingService\022" +
      "n\n\017ScheduleMeeting\022+.schedulePro.meeting" +
      ".ScheduleMeetingRequest\032,.schedulePro.me" +
      "eting.ScheduleMeetingResponse\"\000\022L\n\014ListM" +
      "eetings\022\032.schedulePro.meeting.Empty\032\034.sc" +
      "hedulePro.meeting.Meeting\"\0000\001\022c\n\016AddPart" +
      "icipant\022*.schedulePro.meeting.AddPartici" +
      "pantRequest\032#.schedulePro.meeting.Shared" +
      "Response\"\000\022i\n\021RemoveParticipant\022-.schedu" +
      "lePro.meeting.RemoveParticipantRequest\032#" +
      ".schedulePro.meeting.SharedResponse\"\000\022g\n" +
      "\022NotifyParticipants\022(.schedulePro.meetin" +
      "g.MeetingNotification\032#.schedulePro.meet" +
      "ing.SharedResponse\"\000(\001B\027\n\023schedulePro.me" +
      "etingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_schedulePro_meeting_Meeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schedulePro_meeting_Meeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_Meeting_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "StartTime", "EndTime", "Participants", });
    internal_static_schedulePro_meeting_ScheduleMeetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_schedulePro_meeting_ScheduleMeetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_ScheduleMeetingRequest_descriptor,
        new java.lang.String[] { "Meeting", });
    internal_static_schedulePro_meeting_ScheduleMeetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_schedulePro_meeting_ScheduleMeetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_ScheduleMeetingResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_schedulePro_meeting_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_schedulePro_meeting_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_schedulePro_meeting_SharedResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_schedulePro_meeting_SharedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_SharedResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_schedulePro_meeting_MeetingNotification_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_schedulePro_meeting_MeetingNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_MeetingNotification_descriptor,
        new java.lang.String[] { "MeetingId", "StartTime", "EndTime", });
    internal_static_schedulePro_meeting_AddParticipantRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_schedulePro_meeting_AddParticipantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_AddParticipantRequest_descriptor,
        new java.lang.String[] { "MeetingId", "ParticipantId", });
    internal_static_schedulePro_meeting_RemoveParticipantRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_schedulePro_meeting_RemoveParticipantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_meeting_RemoveParticipantRequest_descriptor,
        new java.lang.String[] { "MeetingId", "ParticipantId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
