// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

public interface ScheduleMeetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.meeting.ScheduleMeetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.schedulePro.meeting.Meeting meeting = 1;</code>
   */
  boolean hasMeeting();
  /**
   * <code>.schedulePro.meeting.Meeting meeting = 1;</code>
   */
  schedulePro.meeting.Meeting getMeeting();
  /**
   * <code>.schedulePro.meeting.Meeting meeting = 1;</code>
   */
  schedulePro.meeting.MeetingOrBuilder getMeetingOrBuilder();
}
