// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetingService.proto

package schedulePro.meeting;

public interface UpdateMeetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.meeting.UpdateMeetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
