// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReminderService.proto

package schedulePro.reminder;

public interface ListRemindersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.reminder.ListRemindersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
