// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReminderService.proto

package schedulePro.reminder;

public final class ReminderServiceOuterClass {
  private ReminderServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_reminder_Reminder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_reminder_Reminder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_reminder_ScheduleReminderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_reminder_ScheduleReminderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_reminder_ScheduleReminderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_reminder_ScheduleReminderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_reminder_ListRemindersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_reminder_ListRemindersRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ReminderService.proto\022\024schedulePro.rem" +
      "inder\032\037google/protobuf/timestamp.proto\032\014" +
      "Shared.proto\"X\n\010Reminder\022\n\n\002id\030\001 \001(\t\022\r\n\005" +
      "title\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\014\n\004time" +
      "\030\004 \001(\003\022\016\n\006userId\030\005 \001(\t\"K\n\027ScheduleRemind" +
      "erRequest\0220\n\010reminder\030\001 \001(\0132\036.schedulePr" +
      "o.reminder.Reminder\"&\n\030ScheduleReminderR" +
      "esponse\022\n\n\002id\030\001 \001(\t\"&\n\024ListRemindersRequ" +
      "est\022\016\n\006userId\030\001 \001(\t2\300\002\n\017ReminderService\022" +
      "s\n\020ScheduleReminder\022-.schedulePro.remind" +
      "er.ScheduleReminderRequest\032..schedulePro" +
      ".reminder.ScheduleReminderResponse\"\000\022_\n\r" +
      "ListReminders\022*.schedulePro.reminder.Lis" +
      "tRemindersRequest\032\036.schedulePro.reminder" +
      ".Reminder\"\0000\001\022W\n\016DeleteReminder\022#.schedu" +
      "lePro.reminder.DeleteRequest\032\036.scheduleP" +
      "ro.reminder.Response\"\000B\030\n\024schedulePro.re" +
      "minderP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          schedulePro.reminder.Shared.getDescriptor(),
        }, assigner);
    internal_static_schedulePro_reminder_Reminder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schedulePro_reminder_Reminder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_reminder_Reminder_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Time", "UserId", });
    internal_static_schedulePro_reminder_ScheduleReminderRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_schedulePro_reminder_ScheduleReminderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_reminder_ScheduleReminderRequest_descriptor,
        new java.lang.String[] { "Reminder", });
    internal_static_schedulePro_reminder_ScheduleReminderResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_schedulePro_reminder_ScheduleReminderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_reminder_ScheduleReminderResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_schedulePro_reminder_ListRemindersRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_schedulePro_reminder_ListRemindersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_reminder_ListRemindersRequest_descriptor,
        new java.lang.String[] { "UserId", });
    com.google.protobuf.TimestampProto.getDescriptor();
    schedulePro.reminder.Shared.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
