// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shared.proto

package schedulePro.reminder;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.reminder.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
