// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReminderService.proto

package schedulePro.reminder;

public interface ScheduleReminderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.reminder.ScheduleReminderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
