// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReminderService.proto

package schedulePro.reminder;

public interface ScheduleReminderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedulePro.reminder.ScheduleReminderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.schedulePro.reminder.Reminder reminder = 1;</code>
   */
  boolean hasReminder();
  /**
   * <code>.schedulePro.reminder.Reminder reminder = 1;</code>
   */
  schedulePro.reminder.Reminder getReminder();
  /**
   * <code>.schedulePro.reminder.Reminder reminder = 1;</code>
   */
  schedulePro.reminder.ReminderOrBuilder getReminderOrBuilder();
}
