// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shared.proto

package schedulePro.reminder;

public final class Shared {
  private Shared() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_reminder_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_reminder_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedulePro_reminder_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedulePro_reminder_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Shared.proto\022\024schedulePro.reminder\"\033\n\r" +
      "DeleteRequest\022\n\n\002id\030\001 \001(\t\",\n\010Response\022\017\n" +
      "\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\tB\030\n\024sched" +
      "ulePro.reminderP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_schedulePro_reminder_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schedulePro_reminder_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_reminder_DeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_schedulePro_reminder_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_schedulePro_reminder_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedulePro_reminder_Response_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
