// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarService.proto

package schedulePro.calendar;

public interface AddEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendar.AddEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
