// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarService.proto

package schedulePro.calendar;

public final class CalendarServiceOuterClass {
  private CalendarServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_AddEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_AddEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_AddEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_AddEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_GetEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_GetEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_UpdateEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_UpdateEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_DeleteEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_DeleteEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_SubscribeToEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_SubscribeToEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_SubscribeToEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_SubscribeToEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendar_SharedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendar_SharedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CalendarService.proto\022\010calendar\"o\n\005Eve" +
      "nt\022\n\n\002id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\023\n\013descrip" +
      "tion\030\003 \001(\t\022\022\n\nstart_time\030\004 \001(\003\022\020\n\010end_ti" +
      "me\030\005 \001(\003\022\020\n\010attendee\030\006 \003(\t\"[\n\017AddEventRe" +
      "quest\022\r\n\005title\030\001 \001(\t\022\023\n\013description\030\002 \001(" +
      "\t\022\022\n\nstart_time\030\003 \001(\003\022\020\n\010end_time\030\004 \001(\003\"" +
      "\036\n\020AddEventResponse\022\n\n\002id\030\001 \001(\t\"\035\n\017GetEv" +
      "entRequest\022\n\n\002id\030\001 \001(\t\"\007\n\005Empty\"j\n\022Updat" +
      "eEventRequest\022\n\n\002id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t" +
      "\022\023\n\013description\030\003 \001(\t\022\022\n\nstart_time\030\004 \001(" +
      "\003\022\020\n\010end_time\030\005 \001(\003\" \n\022DeleteEventReques" +
      "t\022\n\n\002id\030\001 \001(\t\"7\n\030SubscribeToEventRespons" +
      "e\022\n\n\002id\030\001 \001(\t\022\017\n\007success\030\002 \001(\010\"+\n\027Subscr" +
      "ibeToEventRequest\022\020\n\010event_id\030\001 \001(\t\"!\n\016S" +
      "haredResponse\022\017\n\007success\030\001 \001(\0102\260\002\n\017Calen" +
      "darService\022H\n\tAddEvents\022\031.calendar.AddEv" +
      "entRequest\032\032.calendar.AddEventResponse\"\000" +
      "(\0010\001\022=\n\tGetEvents\022\031.calendar.GetEventReq" +
      "uest\032\017.calendar.Event\"\000(\0010\001\0222\n\nListEvent" +
      "s\022\017.calendar.Empty\032\017.calendar.Event\"\0000\001\022" +
      "`\n\021SubscribeToEvents\022!.calendar.Subscrib" +
      "eToEventRequest\032\".calendar.SubscribeToEv" +
      "entResponse\"\000(\0010\001B\030\n\024schedulePro.calenda" +
      "rP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_calendar_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calendar_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_Event_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "StartTime", "EndTime", "Attendee", });
    internal_static_calendar_AddEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calendar_AddEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_AddEventRequest_descriptor,
        new java.lang.String[] { "Title", "Description", "StartTime", "EndTime", });
    internal_static_calendar_AddEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calendar_AddEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_AddEventResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_calendar_GetEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_calendar_GetEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_GetEventRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_calendar_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_calendar_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_calendar_UpdateEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_calendar_UpdateEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_UpdateEventRequest_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "StartTime", "EndTime", });
    internal_static_calendar_DeleteEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_calendar_DeleteEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_DeleteEventRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_calendar_SubscribeToEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_calendar_SubscribeToEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_SubscribeToEventResponse_descriptor,
        new java.lang.String[] { "Id", "Success", });
    internal_static_calendar_SubscribeToEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_calendar_SubscribeToEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_SubscribeToEventRequest_descriptor,
        new java.lang.String[] { "EventId", });
    internal_static_calendar_SharedResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_calendar_SharedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendar_SharedResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
