// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarService.proto

package schedulePro.calendar;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendar.Empty)
    com.google.protobuf.MessageOrBuilder {
}
