// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarService.proto

package schedulePro.calendar;

public interface SharedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendar.SharedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
