// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarService.proto

package schedulePro.calendar;

public interface SubscribeToEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendar.SubscribeToEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
