// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarService.proto

package schedulePro.calendar;

public interface SubscribeToEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendar.SubscribeToEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventIdBytes();
}
