// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package schedulePro.user;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
