// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package schedulePro.user;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LogoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
