// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package schedulePro.user;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_SharedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_SharedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022\004user\"\037\n\rLogoutReque" +
      "st\022\016\n\006userId\030\001 \001(\t\"2\n\014LoginRequest\022\020\n\010us" +
      "ername\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\".\n\rLoginR" +
      "esponse\022\r\n\005token\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\"!" +
      "\n\016SharedResponse\022\017\n\007success\030\001 \001(\010\"\007\n\005Emp" +
      "ty\"!\n\016LogoutResponse\022\017\n\007success\030\001 \001(\010\"5\n" +
      "\017RegisterRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pa" +
      "ssword\030\002 \001(\t\"#\n\020RegisterResponse\022\017\n\007mess" +
      "age\030\001 \001(\t\"$\n\004User\022\n\n\002id\030\001 \001(\t\022\020\n\010usernam" +
      "e\030\002 \001(\t2\347\001\n\013UserService\0222\n\005Login\022\022.user." +
      "LoginRequest\032\023.user.LoginResponse\"\000\0225\n\006L" +
      "ogout\022\023.user.LogoutRequest\032\024.user.Logout" +
      "Response\"\000\022;\n\010Register\022\025.user.RegisterRe" +
      "quest\032\026.user.RegisterResponse\"\000\0220\n\021ListL" +
      "oggedInUsers\022\013.user.Empty\032\n.user.User\"\0000" +
      "\001B\024\n\020schedulePro.userP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_user_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LogoutRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_user_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LoginResponse_descriptor,
        new java.lang.String[] { "Token", "UserId", });
    internal_static_user_SharedResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_SharedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_SharedResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_user_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_user_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_user_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_user_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LogoutResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_user_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_user_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_user_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_user_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RegisterResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
